// src/components/Auth/SelectAccount.vue
<template>
  <div
    class="w-1/2 min-h-[480px] p-6 rounded-xl max-w-[928px] flex flex-col items-center justify-center gap-y-4"
  >
    <div class="flex flex-col items-center justify-center gap-y-3">
      <span class="text-grey-18 font-demibold leading-5 font-bold text-lg"
        >حساب کاربری خود را انتخاب کنید.</span
      >
    </div>

    <div
      class="grid grid-cols-3 gap-4 justify-center items-center"
      v-if="accounts.length > 0"
    >
      <div
        class="unit-card flex flex-col items-center justify-center gap-y-4 rounded-xl p-6 cursor-pointer w-[208px]"
        v-for="(account, index) in accounts"
        :key="account.phoneNumber"
        @click="accountSelected(index)"
      >
        <!-- <img src="../../assets/Images/unit-img.png" alt="" /> -->
        <span class="material-icons-outlined text-grey-12 text-5xl">
          account_circle
        </span>
        <span
          class="text-grey-12 font-bold text-sm leading-5"
          v-if="!!account.firstName && !!account.lastName"
          >{{ account.firstName + " " + account.lastName }}</span
        >
        <span v-else class="text-grey-12 font-bold text-sm leading-5"
          >کاربر</span
        >
      </div>

      <div
        class="unit-card flex flex-col items-center justify-center gap-y-4 rounded-xl p-6 cursor-pointer w-[208px]"
        @click="addAccount()"
      >
        <div
          class="flex flex-col items-center justify-center rounded-full bg-white w-12 h-12 border border-green-12 border-dashed"
        >
          <span class="material-icons-outlined text-grey-12 text-3xl">
            add
          </span>
        </div>
        <span class="text-grey-12 font-bold text-sm leading-5">
          افزودن حساب جدید
        </span>
      </div>
    </div>

    <div v-else class="flex flex-row items-center justify-center">
      <div
        class="unit-card flex flex-col items-center justify-center gap-y-4 rounded-xl p-6 cursor-pointer w-[208px]"
        @click="addAccount()"
      >
        <div
          class="flex flex-col items-center justify-center rounded-full bg-white w-12 h-12 border border-green-12 border-dashed"
        >
          <span class="material-icons-outlined text-grey-12 text-3xl">
            add
          </span>
        </div>
        <span class="text-grey-12 font-bold text-sm leading-5">
          افزودن حساب جدید
        </span>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useAuthStore } from "../../stores/Authentication";

const emit = defineEmits(["is-authenticated", "addAccount"]);

const { accounts, activeAccount } = useAuthStore();
const authStore = useAuthStore();

const router = useRouter();

const accountSelected = (index) => {
  authStore.setActiveAccount(accounts[index]);
  emit("is-authenticated", accounts.length);
};

const addAccount = () => {
  emit("addAccount");
};
</script>

<style lang="scss" scoped></style>

// app/(auth)/select-account/page.tsx
'use client';

import { useAuthStore } from '@/stores/auth-store';
import { useRouter } from 'next/navigation';

export default function SelectAccountPage() {
  const router = useRouter();
  const { accounts, setActiveAccount, addNewAccount } = useAuthStore();

  const handleSelectAccount = (account: any) => {
    setActiveAccount(account);
    router.push('/unit-select');
  };

  const handleAddNewAccount = () => {
    addNewAccount();
    router.push('/login');
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen bg-gray-100">
      <div className="w-full max-w-md p-8 space-y-8 bg-white rounded-lg shadow-md">
        <div className="text-center">
          <h1 className="text-3xl font-bold">انتخاب حساب کاربری</h1>
          <p className="mt-2 text-gray-600">یکی از حساب‌های کاربری زیر را انتخاب کنید.</p>
        </div>

        <div className="space-y-4">
          {accounts.map((account) => (
            <div
              key={account.phoneNumber}
              onClick={() => handleSelectAccount(account)}
              className="flex items-center p-4 space-x-4 border rounded-lg cursor-pointer hover:bg-gray-50"
            >
              <img
                className="w-12 h-12 rounded-full"
                src="/Images/userImage.png"
                alt={`${account.firstName} ${account.lastName}`}
              />
              <div className="flex-1">
                <p className="font-semibold">{`${account.firstName} ${account.lastName}`}</p>
                <p className="text-sm text-gray-500">{account.phoneNumber}</p>
              </div>
            </div>
          ))}
        </div>

        <div className="pt-4 text-center">
          <button
            onClick={handleAddNewAccount}
            className="w-full px-4 py-2 text-white bg-primary rounded-lg hover:bg-primary-dark"
          >
            افزودن حساب کاربری جدید
          </button>
        </div>
      </div>
    </div>
  );
}
